all:
	g++ numeros_random_map.cpp -o numeros_random_map.out
	g++ numeros_random_no_map.cpp -o numeros_random_no_map.out

	g++ espacio_abierto_id.cpp -o id_abierto.out -g
	g++ espacio_abierto_name.cpp -o name_abierto.out -g

	g++ espacio_cerrado_linear_id.cpp -o id_cerrado_linear.out -g
	g++ espacio_cerrado_linear_name.cpp -o name_cerrado_linear.out -g
	
	g++ espacio_cerrado_quadratic_id.cpp -o id_cerrado_quadratic.out -g
	g++ espacio_cerrado_quadratic_name.cpp -o name_cerrado_quadratic.out -g
	
	g++ espacio_cerrado_double_id.cpp -o id_cerrado_double.out -g
	g++ espacio_cerrado_double_name.cpp -o name_cerrado_double.out -g
	
	g++ espacio_map_stl_id.cpp -o map_stl_id.out -g
	g++ espacio_map_stl_name.cpp -o map_stl_name.out -g

	g++ carga_map.cpp -o carga_map.out 